### ISSUE TITLE
Feature regression in 1.7.0, logic helpers ignored in select bodies

### ISSUE THREAD

**Issue by jv-PintoBobcat** [linkedin/dustjs-helpers#134] opened 2015-04-27 16:16 UTC
Given this template:
```
{@select key=selectKey}
    {@eq value=1}One{/eq}
    {@eq value=2}
        Two
        {@eq key=testVal value=5}
            Bug!
        {/eq}
    {/eq}
    {@eq value=3}Three{/eq}
{/select}
```

If `selectKey` is 2 and `testVal` is 5, "Two" is rendered but "Bug!" is not.

Here's a jsfiddle to show this in action.  http://jsfiddle.net/hf67o6un/

**Comment by smfoote** [comment] 2015-04-27 16:27
What version of Dust are you using? I tried your example template on [dustjs.com](http://www.dustjs.com/) and it worked as expected, but it certainly doesn't work in your jsFiddle. I will dig into it, but knowing the Dust version may help.

![image](https://cloud.githubusercontent.com/assets/452458/7352271/757b569e-ecbf-11e4-9e98-9b6d34080684.png)

**Comment by jimmyhchan** [comment] 2015-04-27 16:29
the fiddle indicates `2.7.0` (http://cdnjs.cloudflare.com/ajax/libs/dustjs-linkedin/2.7.0/dust-full.min.js).

**Comment by jimmyhchan** [comment] 2015-04-27 16:29
@jv-PintoBobcat  awesome bug report btw.

**Comment by smfoote** [comment] 2015-04-27 16:44
The issue is in `getSelectState`, which returns an outer select state for any nested `@eq` or `@ne`, etc. If the `selectState` is determined to be true, then the nested `@eq`, `@ne`, etc. are always ignored (see lines 110 and 111 of [lib/dust-helpers.js](https://github.com/linkedin/dustjs-helpers/blob/master/lib/dust-helpers.js).

Because a nested `eq` helper doesn't change the context, I'm not sure what the best way to get around this will be. @sethkinast any ideas?

**Comment by jv-PintoBobcat** [comment] 2015-04-27 16:49
As @jimmyhchan indicated, I was using dust 2.7.0.  However, the bug still occurs using dust 2.6.2.  The issue is definitely due to a change between helpers 1.6.3 and 1.7.0.

@smfoote, the dustjs.com site is still using dust 2.6.2 and helpers 1.6.2.

**Comment by sethkinast** [comment] 2015-04-27 17:05
I thought we had a unit test for this. I'll fix it up.

**Comment by sethkinast** [comment] 2015-04-27 17:27
Caused by a fix for this issue:

    {@select key=foo} {! foo == "bar" !}
      {@eq value="bar"}Yay{/eq}
      {@eq value="baz"}Boo{:else}This was getting invoked{/eq}
    {/select}

**Comment by sethkinast** [comment] 2015-04-27 17:31
Caused by changing the behavior for this issue:

    {@select key=cherry}
      {@eq value="true" type="boolean"}cherry{/eq}
      {@eq key=berry value="true" type="boolean"}berry{/eq}
    {/select}

**Comment by sethkinast** [comment] 2015-04-27 17:52
Thanks for the great bug report! We should have 2.7.1 and 1.7.1 out this week.

**Closed** 2015-04-28 20:15 UTC

**Comment by sethkinast** [comment] 2015-04-29 02:43
1.7.1 has been released to npm.
