### ISSUE TITLE
Helpers 1.6.0 and dustjs-linkedin 2.6.0 can break some apps

### ISSUE THREAD

**Issue by rragan** [linkedin/dustjs-helpers#120] opened 2015-03-10 00:07 UTC
Before this commit for AMD: https://github.com/linkedin/dustjs-helpers/commit/77ccacda93aadf283279dcf46787abe3f6faafca

some apps relied on loading dustjs-helpers to take care of doing the require for dustjs-linkedin and defining dust in the global space. Those apps now break since dust is no longer defined globally.

**Comment by sethkinast** [comment] 2015-03-10 00:10
`dust` should still be global if AMD support isn't on; did something break?

**Comment by sethkinast** [comment] 2015-03-10 00:12
CommonJS should still work as expected:

`module.exports = factory(require('dustjs-linkedin'));`

**Comment by rragan** [comment] 2015-03-10 00:14
Yep, all our server-side  node apps for eBay. They loaded the helpers and relied on the helpers to drag n the global dust variable

**Comment by sethkinast** [comment] 2015-03-10 00:15
It still seems to work for me, firing up a basic Node REPL:

```
skinast-mn1:test skinast$ node
> dust = require('dustjs-helpers')
{ version: '2.6.0',
  debugLevel: 'NONE',
  config: { whitespace: false, amd: false },
  _aliases:
   { ... },
  log: [Function],
  helpers:
   { tap: [Function],
     sep: [Function],
     ...
```

**Comment by rragan** [comment] 2015-03-10 00:18
Maybe we have a compiler mismatch. The generated template that blows up is like:

(function(dust){module.exports=body_0;function body_0(chk,ctx){return chk.h("optimizer-page",ctx,{},{"name":"index","packagePath":"./optimizer.json"}).h("layout-use",ctx,{"block":body_1},{"template":"../../layouts/default-layout.dust"});}body_0.__dustBody=!0;function body_1(chk,ctx){return chk.h("layout-put",ctx,{"block":body_2},{"into":"body"});}body_1.__dustBody=!0;function body_2(chk,ctx){return chk.h("tracking-cookies",ctx,{},{}).h("tracking-images",ctx,{},{}).w("<h1>").h("i18n",ctx,{},{"$key":"SampleApp/index:headers.main"}).w("</h1><div id=\"debug\">").h("i18n-use",ctx,{"block":body_3},{"samp":"SampleApp/index"}).w("</div>");}body_2.__dustBody=!0;function body_3(chk,ctx){return chk.h("i18n",ctx,{},{"$key":"samp:debug.info"}).w("<ul><li>").h("i18n",ctx,{},{"$key":"samp:app.meta"}).w("<ul><li>").h("i18n",ctx,{},{"$key":"samp:page.id"}).w(": ").f(ctx.getPath(false, ["appmeta","pageId"]),ctx,"h").w(" (").f(ctx.getPath(false, ["appmeta","pageName"]),ctx,"h").w(")</li></ul></li><li>").h("i18n",ctx,{},{"$key":"samp:locale"}).w(":<ul><li>").h("i18n",ctx,{},{"$key":"samp:language"}).w(": ").f(ctx.getPath(false, ["locality","language"]),ctx,"h").w("</li><li>").h("i18n",ctx,{},{"$key":"samp:country"}).w(": ").f(ctx.getPath(false, ["locality","country"]),ctx,"h").w("</li><li>").h("i18n",ctx,{},{"$key":"samp:locale"}).w(": ").f(ctx.getPath(false, ["locality","locale"]),ctx,"h").w("</li></ul></li></ul>");}body_3.__dustBody=!0;return body_0;})(dust);

and the last reference to (dust) is killing it I think.

**Comment by sethkinast** [comment] 2015-03-10 00:24
That doesn't look like a compiled template generated by the dust compiler with that `module.exports` line. How does that template get generated and included?

**Comment by rragan** [comment] 2015-03-10 00:25
Need to backtrack how we generate them. They all look like this but neither latest LI one or even ancient akdubya ones look like this

**Comment by rragan** [comment] 2015-03-10 00:26
Probably an issue unique to eBay/PayPal but will investigate

**Comment by sethkinast** [comment] 2015-03-10 00:29
It looks like you're creating modules out of them-- I think the fastest way for you to solve the issue is to remove `dust` out of the closure scope in the step that you do the string munging to insert the module export. So your IIFE would be `(function(){module.exports=...})()` instead.

Because `dust` isn't defined in your module, it's closing over `dust = undefined` and blowing up.

You could also insert `dust = require('dustjs-helpers')` at the top of every compiled moduletemplate.

Dust doesn't yet actually support this use case, which is why you broke :( It's on the roadmap to make templates officially `require`able, though.

Sorry.

**Comment by rragan** [comment] 2015-03-10 00:30
That must be it because we do want our modules to be requireable.

**Comment by sethkinast** [comment] 2015-03-10 00:32
Should be a one-liner change in your custom compiler to prepend `var dust = require('dustjs-helpers');` to the top of each module, then. It won't have a performance impact since dust is already loaded into the require cache!

Technically we were breaking encapsulation before by magically making dust work as a secret global, I think.

**Comment by rragan** [comment] 2015-03-11 00:01
Isolated the change that triggers our failure.

It is the AMD work that emits  the  (dust) being passed to the compiled template. 
https://github.com/linkedin/dustjs/blob/master/lib/compiler.js#L178

Before that, only () was passed to the invocation. Since we are already massaging the returned compiled template to make a module of it, I guess we can take care of adding the var dust = require(...) line.

**Comment by sethkinast** [comment] 2015-03-11 00:06
Right, as I mentioned above, before we were relying on a `dust` variable being available in whatever scope you ended up evaluating your file in-- which is dangerous. Now we expect `dust` to be local to your execution scope, which doesn't break the "normal" use cases, but since you guys are massaging the template to make it a module, it does require a change on your part.

That said, hopefully we can get dust-templates-as-modules as a real thing soon.

**Closed by sethkinast** 2015-03-11 00:06 UTC
